export enum ITeamRole {
  FOUNDER = 'FOUNDER',
  MANAGER = 'MANAGER'
}

export enum IRole {
  ADMIN = 'ADMIN',
  FOUNDER = 'FOUNDER',
  INVESTOR = 'INVESTOR',
  ADVISOR = 'ADVISOR',
  EMPLOYEE = 'EMPLOYEE',
  OPERATOR = 'OPERATOR',
  MANAGER = 'MANAGER',
  ANONYMOUS = 'ANONYMOUS'
}
